// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfc62b_4sbHKkOqyITrsTbF8Kan4Jz-WU',
    appId: '1:701077215139:web:2c48332d84ad0862c2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-flutter-codelab-957bb',
    authDomain: 'fir-flutter-codelab-957bb.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelab-957bb-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-957bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4n5kQwpH_kFveCeRdOWF2sXicBDxyMzs',
    appId: '1:701077215139:android:001a0a14ce6922b1c2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-flutter-codelab-957bb',
    databaseURL: 'https://fir-flutter-codelab-957bb-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-957bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-uvbrVfo-8H-NxBzS9vasFHIqw1grGFw',
    appId: '1:701077215139:ios:e773f88328474973c2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-flutter-codelab-957bb',
    databaseURL: 'https://fir-flutter-codelab-957bb-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-957bb.appspot.com',
    iosBundleId: 'com.example.grayhatproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-uvbrVfo-8H-NxBzS9vasFHIqw1grGFw',
    appId: '1:701077215139:ios:c4eb99a491ad2b95c2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-flutter-codelab-957bb',
    databaseURL: 'https://fir-flutter-codelab-957bb-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-957bb.appspot.com',
    iosBundleId: 'com.example.grayhatproject.RunnerTests',
  );
}
